In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('data/interim/data_version_2.csv')
df.head()

,Unnamed: 0,House Number,City,Parking Spaces,Bedrooms,Bathrooms,Servant Quarters,Kitchens,Store Rooms,price,Purpose,Location,Age Possession,area,price_per_sqft,colony,province,society,property Type
0,0,48022756,Rawalpindi,NaN,5.0,6.0,1.0,2.0,0.0,7.50,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,5445.0,13774.10,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi,Houses
1,1,51560745,Rawalpindi,NaN,5.0,6.0,1.0,2.0,0.0,3.75,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,2968.0,12634.77,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi,Houses
2,2,51815448,Rawalpindi,NaN,5.0,6.0,1.0,2.0,0.0,4.25,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Undefined,2722.0,15613.52,Bahria Town Phase 4,Punjab,Bahria Town Rawalpindi,Houses
3,3,52061409,Rawalpindi,1.0,3.0,3.0,0.0,1.0,0.0,1.50,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,1361.0,11021.31,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi,Houses
4,4,52010487,Rawalpindi,3.0,6.0,6.0,1.0,2.0,1.0,4.75,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",New Property,3812.0,12460.65,Bahria Greens,Punjab,Bahria Town Rawalpindi,Houses

In [4]:
df1=pd.read_csv('data/interim/data_version_2_update.csv')
df1.head()

,House Number,City,House Type,Parking Spaces,Bedrooms,Bathrooms,Servant Quarters,Kitchens,Store Rooms,price,Purpose,Location,Age Possession,area,price_per_sqft,colony,province,society
0,48022756,Rawalpindi,Rawalpindi Houses,NaN,5.0,6.0,1.0,2.0,0.0,7.50,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,5445.0,13774.10,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi
1,51560745,Rawalpindi,Rawalpindi Houses,NaN,5.0,6.0,1.0,2.0,0.0,3.75,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,2968.0,12634.77,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi
2,51815448,Rawalpindi,Rawalpindi Houses,NaN,5.0,6.0,1.0,2.0,0.0,4.25,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Undefined,2722.0,15613.52,Bahria Town Phase 4,Punjab,Bahria Town Rawalpindi
3,52061409,Rawalpindi,Rawalpindi Houses,1.0,3.0,3.0,0.0,1.0,0.0,1.50,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",Relatively New,1361.0,11021.31,Bahria Town Phase 8,Punjab,Bahria Town Rawalpindi
4,52010487,Rawalpindi,Rawalpindi Houses,3.0,6.0,6.0,1.0,2.0,1.0,4.75,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,",New Property,3812.0,12460.65,Bahria Greens,Punjab,Bahria Town Rawalpindi

In [5]:
df.shape

(1519, 19)

In [6]:
df1.shape

(1519, 18)

In [9]:
df3=pd.read_csv('data/processed/feature_selection.csv')
df3.head()

,Unnamed: 0,Parking Spaces,Bedrooms,Bathrooms,Servant Quarters,Kitchens,Store Rooms,area,property Type,Age Possession_New Property,...,colony_UET Housing Society,colony_Valencia Housing Society,colony_Wakeel Colony,colony_Wapda Town,colony_Wapda Town Phase 1,colony_Zafar Al Ahmadi Road,province_Sindh,City_Lahore,City_Rawalpindi,price
0,0,-1.055276,-0.958418,-1.171412,-1.345585,-1.063166,-1.558316,-0.816131,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.50
1,1,0.564499,1.200831,0.619474,-0.037425,0.428759,-0.008064,0.333408,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.75
2,2,-0.245389,-0.958418,-1.171412,-0.037425,-1.063166,-0.008064,-0.177811,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.25
3,3,0.564499,-1.678168,-1.768375,-1.345585,-1.063166,-0.008064,-0.905242,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.15
4,4,-1.055276,-0.238669,0.022512,-1.345585,-2.555091,-1.558316,-0.816131,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.75

In [10]:
df3.shape

(769, 190)

In [12]:
df4=pd.read_csv('data/raw/data_version_1.csv')
df4.head()

,House Number,City,Name,sub_name,description,House Type,Year,Parking Spaces,Bedrooms,Bathrooms,Servant Quarters,Kitchens,Store Rooms,price,Area,Purpose,Location
0,48022756.0,Rawalpindi,Classical Corner House With Huge Lawn Near Fut...,"Bahria Town Phase 8, Bahria Town Rawalpindi, R...",CLASSICAL ELEVATION DESIGN LUXURIOUS FINISHING...,Rawalpindi Houses,2023.0,NaN,5.0,6.0,1.0,2.0,0.0,7.50,1 Kanal,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,"
1,51560745.0,Rawalpindi,Designer House Near To Park & Bahria Expressway,"Bahria Town Phase 8, Bahria Town Rawalpindi, R...",Luxurious House With Elegant Interior Close To...,Rawalpindi Houses,2024.0,NaN,5.0,6.0,1.0,2.0,0.0,3.75,10.9 Marla,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,"
2,51815448.0,Rawalpindi,Slightly Used 10 Marla At Reasonable Price,"Bahria Town Phase 4, Bahria Town Rawalpindi, R...",It's A Few Years Old House Occupied For Very L...,Rawalpindi Houses,NaN,NaN,5.0,6.0,1.0,2.0,0.0,4.25,10 Marla,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,"
3,52061409.0,Rawalpindi,NEW 5 MARLA HOUSE IN BAHRIA TOWN,"Bahria Town Phase 8 - Safari Valley, Bahria To...","House Features Are,5 Marla 2 Portions 3 Spaci...",Rawalpindi Houses,2024.0,1.0,3.0,3.0,0.0,1.0,0.0,1.50,5 Marla,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,"
4,52010487.0,Rawalpindi,Triple Story Corner Plus Lawn 14 Marla Used Ho...,"Bahria Greens - Overseas Enclave - Sector 2, B...",14 Marla Corner Plus Basement Triple Story Use...,Rawalpindi Houses,2019.0,3.0,6.0,6.0,1.0,2.0,1.0,4.75,14 Marla,For Sale,"Bahria Town Rawalpindi, Rawalpindi, Punjab,"

In [13]:
df4.shape

(1520, 17)

In [15]:
df4[df4['House Number'].isnull()]

,House Number,City,Name,sub_name,description,House Type,Year,Parking Spaces,Bedrooms,Bathrooms,Servant Quarters,Kitchens,Store Rooms,price,Area,Purpose,Location
1238,NaN,Karachi,4 Bed Living Apartment Available In Booking At...,"Callachi Cooperative Housing Society, Karachi,...",*CALLACHI ICON*A PROJECT BY *ZIFAN GROUP* IN C...,Karachi Flats,2021.0,4.0,4.0,5.0,1.0,2.0,1.0,3.25,NaN,NaN,"Callachi Cooperative Housing Society, Karachi,..."